### PR TITLE
Landing page finished

### PR DESCRIPTION
**Pull request by Hai5edfm**
The landing page was finished, added the fonts, styles, responsive, and test for the buttons
Also were added some changes of the Menu, layout, styles, transition, the finished will be sent in another PR with its tests

Thir PR also includes the file-loader dependency to load by now the img files and framer-motion to make the animations

### CODE REVIEW

**Comment by LilianaRestrepoTorres** [comment]
It was added this component:
[`[src/components/Menu/NavLinks/index.js]`]([src/components/Menu/NavLinks/index.js](https://github.com/C10-Ghibli-s/FE-Studio-Ghibli-Tracker/pull/36/files#diff-3f3ea3ba855853f4814ead0c950eb87c08ce6189da6f2115b02ec34aa1671e38))
And also this:
[`[src/components/Menu/NavLinks/navLink/index.js]`]([src/components/Menu/NavLinks/navLink/index.js](https://github.com/C10-Ghibli-s/FE-Studio-Ghibli-Tracker/pull/36/files#diff-3442610a93a2144b09ab39fdd63f0e5649d40707761b7745b6bc26f863f372f5))
In my opinion `/navLink` should be at the same level of `/NavLinks`, which is in `src/components/`

**Comment by LilianaRestrepoTorres** [comment]
I'd like to know which means the name (`export { CTA_RegisterButton };`) of the component: [`[src/components/RegisterButton/index.js]`]([src/components/RegisterButton/index.js](https://github.com/C10-Ghibli-s/FE-Studio-Ghibli-Tracker/pull/36/files#diff-8d99dc31ffdc790f8618faba400682071566c9c324f27c0ae5c105a3b7bf687a))

**Comment by LilianaRestrepoTorres** [comment]
Are we using `import TestRenderer from 'react-test-renderer';` to add snapshot test? or what is the difference between that one and ` import { render } from "@testing-library/react";`?

**Comment by LilianaRestrepoTorres** [comment]
Do we need to add

- [`[src/pages/profile/index.js]`]([src/pages/profile/index.js](https://github.com/C10-Ghibli-s/FE-Studio-Ghibli-Tracker/pull/36/files#diff-8a012c36b7eafeacfe98073eb4f37335d8079cd114c96130943af209cd347b47))
- [`[src/pages/scores/index.js]`]([src/pages/scores/index.js](https://github.com/C10-Ghibli-s/FE-Studio-Ghibli-Tracker/pull/36/files#diff-732d740bd13bde9a5fb6a5f0d9913b8d1c8f4666da8fd4dfd0f98ee77ba62797))
- [`[src/pages/watched/index.js]`]([src/pages/watched/index.js](https://github.com/C10-Ghibli-s/FE-Studio-Ghibli-Tracker/pull/36/files#diff-e7c16fde71e762152ab4b50e4c2453b00ac7ac6a1f937602d7ca41f5446f254a))

All of these pages are including 'Filter Engine'. Is it necessary? We have that functionality as a component. These pages also are containing css, should we create file.css or is this the correct practice?

--
Those are my comments! :slightly_smiling_face: It was well done. I'll wait to solve this questions to proceed merging into the original.

**Review by LilianaRestrepoTorres — CHANGES_REQUESTED** [review]
Those are my comments! 🙂 It was well done. I'll wait to solve this questions to proceed merging into the original.

**Comment by AreYouIvan** [comment]
I think coverage/ is still being tracked in git, I'm going to delete them with your permission 🥵

**Review by AreYouIvan — COMMENTED** [review]
It seems good, just waiting for the requested changes, in the future I think that we can make a copy of the pages but as empty 😉

**Pull request merged**
